language: php

php:
    - 7.1
    - 7.2

env:
    - SYMFONY_VERSION=3.4.*
    - SYMFONY_VERSION=4.1.*
    - SYMFONY_VERSION=4.2.*

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer require symfony/dependency-injection:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist
    - composer require symfony/http-kernel:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist
    - composer require symfony/proxy-manager-bridge:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist
    - composer require --dev symfony/framework-bundle:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist
    - composer update --prefer-dist

script:
    - composer validate --strict

    - vendor/bin/phpstan analyse -c phpstan.neon -l max src -vvv

    - vendor/bin/behat -f progress --strict -vvv --no-interaction
