language: php

php:
    - 7.1

env:
    - SYMFONY_VERSION=~3.3.0
    - SYMFONY_VERSION=~3.4.0 MINIMUM_STABILITY=beta
    - SYMFONY_VERSION=~4.0.0 MINIMUM_STABILITY=beta

cache:
    directories:
        - vendor

before_install:
    - phpenv config-rm xdebug.ini || true

    - |
        if [[ ! -z $MINIMUM_STABILITY ]]; then
            composer config minimum-stability $MINIMUM_STABILITY
        fi
    - composer require --no-update symfony/http-kernel:$SYMFONY_VERSION symfony/framework-bundle:$SYMFONY_VERSION

install:
    - composer update --prefer-dist

script:
    - composer validate --strict

    - vendor/bin/behat --strict -vvv --no-interaction
