language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0snapshot'

env:
    - SYMFONY_VERSION=4.4.*
    - SYMFONY_VERSION=5.1.*

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer self-update --2 # Upgrade to Compose 2 (needed for PHP 8 support), only needed while it's not installed by default

install:
    - composer require symfony/dependency-injection:${SYMFONY_VERSION} --no-update --no-scripts
    - composer require symfony/http-kernel:${SYMFONY_VERSION} --no-update --no-scripts
    - composer require symfony/proxy-manager-bridge:${SYMFONY_VERSION} --no-update --no-scripts

    - composer require --dev symfony/browser-kit:${SYMFONY_VERSION} --no-update --no-scripts
    - composer require --dev symfony/framework-bundle:${SYMFONY_VERSION} --no-update --no-scripts
    - composer require --dev symfony/process:${SYMFONY_VERSION} --no-update --no-scripts
    - composer require --dev symfony/yaml:${SYMFONY_VERSION} --no-update --no-scripts

    - composer update

script:
    - composer check

    - vendor/bin/behat -f progress --strict -vvv --no-interaction
